-- Cleansed Dim_Products Tables --
SELECT P.[ProductKey]
      ,P.[ProductAlternateKey] as ProductItemCode
      --,[ProductSubcategoryKey]
      --,[WeightUnitMeasureCode]
      --,[SizeUnitMeasureCode]
      ,P.[EnglishProductName] as [Product Name]
	  ,PS.EnglishProductSubcategoryName as [Sub Category]
	  ,PC.EnglishProductCategoryName as [Product Category]
      --,[SpanishProductName]
      --,[FrenchProductName]
      --,[StandardCost]
      --,[FinishedGoodsFlag]
      ,P.[Color] as [Product Color]
      --,[SafetyStockLevel]
      --,[ReorderPoint]
      --,[ListPrice]
      ,P.[Size] as [Product Size]
      --,[SizeRange]
      --,[Weight]
      --,[DaysToManufacture]
      ,P.[ProductLine] as [Product Line]
      --,[DealerPrice]
      --,[Class]
      --,[Style]
      ,P.[ModelName] as [Product Model Name]
      --,[LargePhoto]
      ,P.[EnglishDescription] as [Product Description]
      --,[FrenchDescription]
      --,[ChineseDescription]
      --,[ArabicDescription]
      --,[HebrewDescription]
      --,[ThaiDescription]
      --,[GermanDescription]
      --,[JapaneseDescription]
      --,[TurkishDescription]
      --,[StartDate]
      --,[EndDate]
      ,ISNULL (P.[Status], 'Oudated') as [Product Status]
  FROM dbo.DimProduct as P 
  left join dbo.DimProductSubcategory as PS on P.ProductSubcategoryKey = PS.ProductSubcategoryKey
  left join dbo.DimProductCategory as PC on PS.ProductCategoryKey = PC.ProductCategoryKey
  ORDER BY P.ProductKey ASC
